name: SpeedBlock
version: 1.0.0
main: com.puchidex.speedblock.SpeedBlockPaper
description: Backend server whitelist plugin for Velocity
author: Puchidex
api-version: '1.16'

commands:
  speedblock:
    description: Manage server whitelists
    usage: /speedblock <create|reload|server> [args...]
    permission: speedblock.admin
    aliases: [sb]

permissions:
  speedblock.admin:
    description: Allows access to all SpeedBlock commands
    default: op